
name: dbt_project
version: '1.0.0'
config-version: 2

profile: dbt_project

model-paths: ["models"]
test-paths: ["tests"]

models:
  dbt_project:
    staging:
      +materialized: view        # staging = views (no storage cost)
    intermediate:
      +materialized: view
    marts:
      +materialized: table       # marts = tables (fast to query)
